-- Migration: Create signatures storage bucket
-- Executed at: 2026-05-02T06:07:39Z
-- Generated by Could Code

insert into storage.buckets (id, name, public) values ('signatures', 'signatures', true) on conflict (id) do nothing;
