-- Migration: Create invoices and settings tables, along with storage bucket for signatures
-- Executed at: 2026-05-02T06:05:04Z
-- Generated by Could Code

-- Create settings table
CREATE TABLE IF NOT EXISTS public.settings (
    id int PRIMARY KEY DEFAULT 1,
    signature_url text,
    google_sheets_webhook_url text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT single_row CHECK (id = 1)
);

-- Insert default row
INSERT INTO public.settings (id) VALUES (1) ON CONFLICT DO NOTHING;

-- Create invoices table
CREATE TABLE IF NOT EXISTS public.invoices (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamptz DEFAULT now(),
    customer_name text NOT NULL,
    company_name text NOT NULL,
    address text NOT NULL,
    contact_number text NOT NULL,
    email text NOT NULL,
    product_details text NOT NULL,
    quantity int NOT NULL,
    price numeric NOT NULL,
    payment_terms text NOT NULL,
    delivery_terms text NOT NULL,
    total_amount numeric NOT NULL,
    sync_status text DEFAULT 'pending'
);

-- Enable RLS (allow public insert for forms, but maybe require auth for reading - for simplicity we'll allow anon read/write since it's a link-based form without auth mentioned)
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read settings" ON public.settings FOR SELECT USING (true);
CREATE POLICY "Allow public update settings" ON public.settings FOR UPDATE USING (true);

ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public insert invoices" ON public.invoices FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read invoices" ON public.invoices FOR SELECT USING (true);

-- Create storage bucket for signatures
INSERT INTO storage.buckets (id, name, public) VALUES ('signatures', 'signatures', true) ON CONFLICT DO NOTHING;

-- Set up storage policies for signatures bucket
CREATE POLICY "Allow public read signatures" ON storage.objects FOR SELECT USING (bucket_id = 'signatures');
CREATE POLICY "Allow public insert signatures" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'signatures');
CREATE POLICY "Allow public update signatures" ON storage.objects FOR UPDATE USING (bucket_id = 'signatures');
CREATE POLICY "Allow public delete signatures" ON storage.objects FOR DELETE USING (bucket_id = 'signatures');
